### PR TITLE
Support wide characters

### PR DESCRIPTION
**Pull request by mattn**
``` diff
diff --git a/example/main.go b/example/main.go
index c59b2e7..3200da5 100644
--- a/example/main.go
+++ b/example/main.go
@@ -17,10 +17,10 @@ var hackers = []hacker{

 func main() {
    table := uitable.New()
-   table.MaxColWidth = 50
+   table.MaxColWidth = 39

    fmt.Println("==> List")
-   table.AddRow("NAME", "BIRTHDAY", "BIO")
+   table.AddRow("名前", "誕生日", "BIO")
    for _, hacker := range hackers {
        table.AddRow(hacker.Name, hacker.Birthday, hacker.Bio)
    }
@@ -28,11 +28,11 @@ func main() {

    fmt.Print("\n==> Details\n")
    table = uitable.New()
-   table.MaxColWidth = 80
+   table.MaxColWidth = 70
    table.Wrap = true
    for _, hacker := range hackers {
-       table.AddRow("Name:", hacker.Name)
-       table.AddRow("Birthday:", hacker.Birthday)
+       table.AddRow("名前:", hacker.Name)
+       table.AddRow("誕生日:", hacker.Birthday)
        table.AddRow("Bio:", hacker.Bio)
        table.AddRow("") // blank
    }
```

### CODE REVIEW

**Comment by gosuri** [comment]
Sweet! Thanks!

**Comment by mattn** [comment]
Maybe, Wrap should be fixed also, I guess.

**Comment by gosuri** [comment]
Please feel free to send a patch if you can

**Comment by mattn** [comment]
will do :)

**Pull request merged**
